project:
  type: website
  output-dir: docs
  resources: 
    - CNAME
website:
  #title: "Feed"
  image: "SAP_website-image_TRANSPARENT.png"
  favicon: "SAP_website_favicon.png"
  navbar: 
    logo: "SAP_website-image_TRANSPARENT.png"
    logo-alt: "Sustainable aquafeeds project"
    logo-href: /home.html 
    collapse-below: lg
    right:
      - text: Home
        href: index.qmd
      - text: Our approach
        href: ourapproach.qmd
      - text: Our team
        href: ourteam.qmd
      - text: Our research 
        href: ourresearch.qmd
      - text: News
        href: news.qmd
      - icon: github
        href: https://github.com/Sustainable-Aquafeeds-Project
      - icon: envelope
        href: mailto:julia.blanchard@utas.edu.au
  page-footer:
      background: "#094867"
      
      left:  Copyright &copy; 2023 [Sustainable Aquafeeds Project](https://sustainable-aquafeeds-project.github.io/)
      center: |
        This research is co-funded  by the Australian Government through the Australian Research
        Council (ARC)Linkage Grant Scheme
      right: "Built using [Quarto](https://quarto.org/)"

  #  right: |
   #   [Terms & Conditions](/ts-and-cs.qmd)    
format:
  html:
    theme: [lux,custom.scss]
    #css: style.css
    
editor: visual

